In [6]:
%load_ext autoreload
%autoreload 2
from projetressourcesagricoles.data import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
csv_path = "/home/mickh/code/mathieudimartino/projet-ressources-agricoles/raw_data/tmp/merged.csv"
df = pd.read_csv(csv_path, low_memory=False)

In [21]:
year_min = 1980
year_max = 2015

In [18]:
get_years(df, year_min, year_max)

,y1961,y1961f,y1962,y1962f,y1963,y1963f,y1964,y1964f,y1965,y1965f,...,y2011,y2011f,y2012,y2012f,y2013,y2013f,y2014,y2014f,y2015,y2015f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29067,11841.0,Agrégat,12192.0,Agrégat,17915.0,Agrégat,16371.0,Agrégat,11343.0,Agrégat,...,28093.0,Agrégat,30020.0,Agrégat,31000.0,Agrégat,32871.0,Agrégat,30800.0,Agrégat
29068,30188.0,Agrégat,19552.0,Agrégat,23726.0,Agrégat,33706.0,Agrégat,21395.0,Agrégat,...,230100.0,Agrégat,233000.0,Agrégat,236700.0,Agrégat,240000.0,Agrégat,245000.0,Agrégat
29069,83010.0,Agrégat,79368.0,Agrégat,93872.0,Agrégat,135037.0,Agrégat,90085.0,Agrégat,...,40000.0,Agrégat,40000.0,Agrégat,40000.0,Agrégat,37554.0,Agrégat,35608.0,Agrégat
29070,6000.0,Agrégat,5000.0,Agrégat,4000.0,Agrégat,3000.0,Agrégat,3000.0,Agrégat,...,10700.0,Agrégat,12050.0,Agrégat,11631.0,Agrégat,15446.0,Agrégat,15646.0,Agrégat
29071,127000.0,Agrégat,135000.0,Agrégat,162000.0,Agrégat,174000.0,Agrégat,173920.0,Agrégat,...,671183.0,Agrégat,678876.0,Agrégat,686313.0,Agrégat,700303.0,Agrégat,748746.0,Agrégat

In [22]:
select_rangeyears(df, year_min, year_max)

,Code pays déclarant,Code pays partenaire,Code Produit,Code Élément,Élément,Unité,y1980,y1980f,y1981,y1981f,...,y2011,y2011f,y2012,y2012f,y2013,y2013f,y2014,y2014f,y2015,y2015f
0,1,2,527,5610,Importations - Quantité,tonnes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,1,2,527,5622,Importations - Valeur,US$,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,1,2,221,5610,Importations - Quantité,tonnes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2,221,5622,Importations - Valeur,US$,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,633,5610,Importations - Quantité,tonnes,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29067,3,3,1726,5510,Production,tonnes,22160.0,Agrégat,24300.0,Agrégat,...,28093.0,Agrégat,30020.0,Agrégat,31000.0,Agrégat,32871.0,Agrégat,30800.0,Agrégat
29068,3,3,1720,5510,Production,tonnes,98800.0,Agrégat,119100.0,Agrégat,...,230100.0,Agrégat,233000.0,Agrégat,236700.0,Agrégat,240000.0,Agrégat,245000.0,Agrégat
29069,3,3,1723,5510,Production,tonnes,278100.0,Agrégat,304400.0,Agrégat,...,40000.0,Agrégat,40000.0,Agrégat,40000.0,Agrégat,37554.0,Agrégat,35608.0,Agrégat
29070,3,3,1729,5510,Production,tonnes,4550.0,Agrégat,5000.0,Agrégat,...,10700.0,Agrégat,12050.0,Agrégat,11631.0,Agrégat,15446.0,Agrégat,15646.0,Agrégat
29071,3,3,1735,5510,Production,tonnes,312000.0,Agrégat,325000.0,Agrégat,...,671183.0,Agrégat,678876.0,Agrégat,686313.0,Agrégat,700303.0,Agrégat,748746.0,Agrégat