In [1]:
%load_ext autoreload
%autoreload 2
from projetressourcesagricoles.data import *

In [4]:
countrycodes = 68
elementcodes = '*'
partnercodes = [106]
itemcodes = [515]

filtered_df = get_data(countrycodes_list = countrycodes, 
         elementcodes_list = elementcodes, 
         partnercodes_list = partnercodes, 
         itemcodes_list = itemcodes)
filtered_df

,Code pays déclarant,Pays,Code pays partenaire,Pays_partenaire,Code Produit,Produit,Code Élément,Élément,Unité,y1961,...,y2016,y2016f,y2017,y2017f,y2018,y2018f,y2019,y2019f,y2020,y2020f
0,68,France,68,France,515,Pommes,5910,Exportations - Quantité,tonnes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68,France,68,France,515,Pommes,5922,Exportations - Valeur,US$,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68,France,68,France,515,Pommes,5510,Production,tonnes,2142000.0,...,1823123.0,NaN,1695949.0,NaN,1740350.0,NaN,1753500.0,NaN,NaN,NaN
3,68,France,106,Italie,515,Pommes,5610,Importations - Quantité,tonnes,NaN,...,31499.0,NaN,28343.0,NaN,30340.0,NaN,36524.0,NaN,27881.0,NaN
4,68,France,106,Italie,515,Pommes,5622,Importations - Valeur,US$,NaN,...,21371.0,NaN,27053.0,NaN,27063.0,NaN,23396.0,NaN,19238.0,NaN
5,68,France,106,Italie,515,Pommes,5910,Exportations - Quantité,tonnes,NaN,...,8939.0,NaN,10401.0,NaN,9452.0,NaN,8185.0,NaN,8296.0,NaN
6,68,France,106,Italie,515,Pommes,5922,Exportations - Valeur,US$,NaN,...,3113.0,NaN,5924.0,NaN,6482.0,NaN,4192.0,NaN,5389.0,NaN