In [20]:
%load_ext autoreload
%autoreload 2
from projetressourcesagricoles.data import get_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [22]:
countrycodes_list = 68
elementcodes_list = 5510
partnercodes_list = '*'
itemcodes_list = '*'
year_start = 2011
year_end = 2018
inner_labels = False

get_data(countrycodes_list = countrycodes_list, elementcodes_list = elementcodes_list, 
         partnercodes_list = partnercodes_list, itemcodes_list = itemcodes_list, 
         year_start = year_start, year_end = year_end, inner_labels = inner_labels)

,Code pays déclarant,Pays,Code pays partenaire,Pays_partenaire,Code Produit,Produit,Code Élément,Élément,Unité,y2011,...,y2014,y2014f,y2015,y2015f,y2016,y2016f,y2017,y2017f,y2018,y2018f
0,68,France,68,France,221,Amandes non décortiquées,5510,Production,tonnes,635.0,...,1067.0,NaN,780.0,NaN,1139.0,NaN,1078.0,NaN,1130.0,NaN
1,68,France,68,France,515,Pommes,5510,Production,tonnes,1762640.0,...,1847551.0,NaN,1968628.0,NaN,1823123.0,NaN,1695949.0,NaN,1740350.0,NaN
2,68,France,68,France,526,Abricots,5510,Production,tonnes,148648.0,...,175760.0,NaN,159375.0,NaN,603268.0,NaN,654938.0,NaN,112890.0,NaN
3,68,France,68,France,366,Artichauts,5510,Production,tonnes,50589.0,...,38354.0,NaN,43992.0,NaN,38760.0,NaN,47249.0,NaN,47190.0,NaN
4,68,France,68,France,367,Asperges,5510,Production,tonnes,22330.0,...,20559.0,NaN,20089.0,NaN,18721.0,NaN,21693.0,NaN,20680.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,68,France,68,France,1726,NaN,5510,Production,tonnes,1059101.0,...,868207.0,Agrégat,979730.0,Agrégat,813427.0,Agrégat,1060443.0,Agrégat,835170.0,Agrégat
103,68,France,68,France,1720,NaN,5510,Production,tonnes,7479953.0,...,8130420.0,Agrégat,7169938.0,Agrégat,7015977.0,Agrégat,8609681.0,Agrégat,7860380.0,Agrégat
104,68,France,68,France,1723,NaN,5510,Production,tonnes,37944864.0,...,40394390.0,Agrégat,36125392.0,Agrégat,37186932.0,Agrégat,49160551.0,Agrégat,39914030.0,Agrégat
105,68,France,68,France,1729,NaN,5510,Production,tonnes,52964.0,...,55555.0,Agrégat,59904.0,Agrégat,61984.0,Agrégat,50524.0,Agrégat,66270.0,Agrégat
106,68,France,68,France,1735,NaN,5510,Production,tonnes,5253569.0,...,4988317.0,Agrégat,4932846.0,Agrégat,5389131.0,Agrégat,5511958.0,Agrégat,4493920.0,Agrégat